#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export LC_CTYPE="en_US.UTF-8"
export EDITOR=vim
export VISUAL=vim
if [ -f ~/.homebrew_gh_api_token ]; then
	export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.homebrew_gh_api_token)
fi

# aliases
alias ff='find ./ -iname $*'
alias vi='vim'
alias ssh-kr='ssh-keygen -R $*'

# I don't like questions
unalias rm
unalias cp
unalias mv

# Avoid this boring message "do you wish to see all N possibilities?
export LISTMAX=1000

# Disable correct completely, it's PITA
unsetopt correct correctall

# Add ~/bin to PATH
export PATH=${PATH}:~/bin

# alt+. insert last word from previous command
bindkey -M viins '\e.' insert-last-word

setopt clobber

# Fix git reset HEAD^
unsetopt nomatch

# keychain
if which -s keychain >/dev/null 2>&1; then
	eval $(keychain --eval id_rsa)
fi

# iTerm2 integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# Disable noglob scp
unalias scp
