#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_COLLATE="C"
export EDITOR=nvim
export VISUAL=nvim
export ANDROID_HOME=/usr/local/opt/android-sdk
if [ -f ~/.homebrew_gh_api_token ]; then
	export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.homebrew_gh_api_token)
fi

# aliases
alias ff='find ./ -iname $*'
alias vi='nvim'
#alias vim='vim -p'
alias gvim='nvim'
alias ssh-kr='ssh-keygen -R $*'
alias weather='curl -s http://v2.wttr.in/Iracemapolis'

# If it's a centos / ubuntu, enable do_configure
unset ID
test -f /etc/os-release \
	&& source /etc/os-release

if [ "${ID}" = "centos" -o "${ID}" = "ubuntu" ]; then
	alias do_configure='./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info'
fi

# I don't like questions
unalias rm
unalias cp
unalias mv

# Avoid this boring message "do you wish to see all N possibilities?
export LISTMAX=1000

# Disable correct completely, it's PITA
unsetopt correct correctall

# Add ~/bin to PATH
PATH=${PATH}:~/bin:~/.local/bin

# macOS specific bits
if [[ "$OSTYPE" == darwin* ]]; then
	export HOMEBREW_NO_ENV_HINTS=1
	PATH="/opt/homebrew/bin:$PATH"
	PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
fi

if $(which go >/dev/null 2>&1); then
	PATH=$PATH:$(go env GOPATH)/bin
fi

export PATH

# alt+. insert last word from previous command
bindkey -M viins '\e.' insert-last-word

setopt clobber

# Fix git reset HEAD^
unsetopt nomatch

# iTerm2 integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# Disable noglob scp
unalias scp

# use a sane git
test -f /opt/rh/rh-git218/enable \
	&& source /opt/rh/rh-git218/enable

if which ondir >/dev/null 2>&1; then
	chpwd() {
		ondir=$(which ondir)
		eval "`${ondir} \"$OLDPWD\" \"$PWD\"`"
	}
fi

# Wayland
if [ -z "$XDG_RUNTIME_DIR" ]; then
	export XDG_RUNTIME_DIR=/tmp/sway
fi
if [ ! -d "$XDG_RUNTIME_DIR" ]; then
	mkdir -p $XDG_RUNTIME_DIR
	chmod 0700 $XDG_RUNTIME_DIR
fi
